{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: transaction-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: transaction-service
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: bleatbank
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: transaction-service
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 30s
      scrapeTimeout: 10s
{{- end }}
