global:
  namespace: banking
  imagePullPolicy: IfNotPresent
  frontendOrigin: http://bleatbank.local

images:
  frontend:
    repository: chigoldd/chibank-frontend
    tag: "v1.1.0"
  userService:
    repository: chigoldd/chibank-user-service
    tag: "v1.1.0"
  transactionService:
    repository: chigoldd/chibank-transaction-service
    tag: "v1.1.0"
  activityService:
    repository: chigoldd/chibank-activity-service
    tag: "v1.1.0"

frontend:
  replicas: 1
  port: 8080
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

userService:
  replicas: 1
  port: 8000
  resources:
    requests:
      cpu: 50m
      memory: 96Mi
    limits:
      cpu: 250m
      memory: 256Mi

transactionService:
  replicas: 2
  port: 8080
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 6
    targetCPUUtilizationPercentage: 80
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

activityService:
  replicas: 1
  port: 8001
  resources:
    requests:
      cpu: 50m
      memory: 96Mi
    limits:
      cpu: 250m
      memory: 256Mi

postgres:
  image:
    repository: postgres
    tag: "15"
  database: bankingdb
  username: banking_user
  password: change-me
  port: 5432
  storage: 1Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

redis:
  image:
    repository: redis
    tag: "7"
  port: 6379
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

kafka:
  image:
    repository: confluentinc/cp-kafka
    tag: "8.1.1"
  port: 29092
  controllerPort: 29093
  externalPort: 9092
  jmxPort: 9101
  clusterId: MkU3OEVBNTcwNTJENDM2Qk
  resources:
    requests:
      cpu: 250m
      memory: 768Mi
    limits:
      cpu: 750m
      memory: 1Gi

ingress:
  enabled: true
  className: nginx
  host: bleatbank.local

monitoring:
  enabled: true
  releaseLabel: monitoring
  serviceMonitor:
    enabled: true
  prometheusRules:
    enabled: true
  alerting:
    enabled: false
    slack:
      channel: "#banking-alerts"
      secretName: alertmanager-slack-webhook
      secretKey: webhook-url
  exporters:
    enabled: true
    postgres:
      image: prometheuscommunity/postgres-exporter:v0.17.1
      port: 9187
    redis:
      image: oliver006/redis_exporter:v1.67.0
      port: 9121
    kafka:
      image: danielqsj/kafka-exporter:v1.8.0
      port: 9308
